# Generated by Django 3.0 on 2020-05-10 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='房號')),
                ('room_create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建房間時間')),
                ('area', models.CharField(choices=[('1', '進階區'), ('2', '體驗區')], default='1', max_length=1, verbose_name='區域')),
                ('state', models.CharField(choices=[('1', 'Waiting'), ('2', 'Playing'), ('3', 'Finished')], default='1', max_length=1, verbose_name='遊戲狀態')),
                ('base', models.PositiveIntegerField(default=1, verbose_name='底數')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='台')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='遊戲開始時間')),
                ('total_commission', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='總抽水金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldFlowSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='發行總金額')),
                ('available_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='總可用餘額')),
                ('flow_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='總流動金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='玩家ID')),
                ('nick_name', models.CharField(max_length=200, verbose_name='暱稱')),
                ('line_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Line ID')),
                ('line_profile_url', models.URLField(blank=True, null=True, verbose_name='Line 圖片連結')),
                ('real_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='帳號名稱')),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='手機號碼')),
                ('permission_type', models.CharField(choices=[('1', '一般玩家'), ('2', '代理玩家')], default='1', max_length=1, verbose_name='會員身份')),
                ('is_lock', models.BooleanField(default=False, verbose_name='帳號封鎖？')),
                ('gold_total', models.PositiveIntegerField(default=0, verbose_name='金幣')),
                ('agent_playerid', models.PositiveIntegerField(blank=True, null=True, verbose_name='上層代理')),
                ('score', models.IntegerField(default=0, verbose_name='正負分')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('register_mac_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC位址')),
                ('register_imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.PositiveIntegerField(default=0, verbose_name='贈送人ID')),
                ('receiver_id', models.PositiveIntegerField(default=0, verbose_name='接收人ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gamecore.Player')),
                ('four_MJ', models.BooleanField(default=False, verbose_name='四人麻將')),
                ('two_MJ', models.BooleanField(default=False, verbose_name='二人麻將')),
                ('niuniu_poker', models.BooleanField(default=False, verbose_name='牛牛')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(default=0, verbose_name='來源玩家ID')),
                ('type', models.CharField(choices=[('4', '介紹金'), ('5', '抽水')], default='5', max_length=1, verbose_name='類別')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('11', '遊戲儲值'), ('12', '贈送'), ('13', '受贈'), ('14', '抽水錢包提領')], default='11', max_length=2, verbose_name='類別')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('1', '登入'), ('2', '開啟新房間'), ('3', '離開房間')], default='1', max_length=1, verbose_name='IP Type')),
                ('mac_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC 位址')),
                ('iemi', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player')),
            ],
        ),
        migrations.CreateModel(
            name='IntroductionGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveIntegerField(default=0, verbose_name='代理ID')),
                ('match_count', models.PositiveIntegerField(default=0, verbose_name='符合條件四人圈數')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('withdraw_date', models.DateTimeField(blank=True, null=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoldFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '發行金幣'), ('2', '補償'), ('3', '信用卡儲值'), ('4', '介紹金'), ('5', '抽水'), ('6', '體驗金')], default='2', max_length=1, verbose_name='類別')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamecore.Player', verbose_name='目標玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameRun',
            fields=[
                ('run_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='遊戲局號(回播碼)')),
                ('seqno', models.PositiveSmallIntegerField(default=1, verbose_name='場次')),
                ('seqno_start_date', models.DateTimeField(verbose_name='場次開始時間')),
                ('run_name', models.CharField(max_length=10, verbose_name='局')),
                ('base', models.PositiveIntegerField(default=1, verbose_name='底數')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='台')),
                ('player1', models.PositiveIntegerField(verbose_name='玩家1ID')),
                ('player2', models.PositiveIntegerField(verbose_name='玩家2ID')),
                ('player3', models.PositiveIntegerField(verbose_name='玩家3ID')),
                ('player4', models.PositiveIntegerField(verbose_name='玩家4ID')),
                ('win_player', models.PositiveIntegerField(blank=True, null=True, verbose_name='胡牌')),
                ('lost_won_player', models.PositiveIntegerField(blank=True, null=True, verbose_name='放槍')),
                ('win_self_hand_player', models.PositiveIntegerField(blank=True, null=True, verbose_name='自摸')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.GameRoom')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.PositiveIntegerField(default=0, verbose_name='胡牌')),
                ('lost_won', models.PositiveIntegerField(default=0, verbose_name='放槍')),
                ('win_self_hand', models.PositiveIntegerField(default=0, verbose_name='自摸')),
                ('highest_banker_count', models.IntegerField(default=0, verbose_name='當日最高連莊次數')),
                ('score', models.IntegerField(default=0, verbose_name='總成績')),
                ('start_gold', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='起始金額')),
                ('settle_gold', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='結算金額')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='官方抽水金額')),
                ('agent_commisson', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='代理抽水金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('game_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.GameRun', verbose_name='遊戲局號(回播碼)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commisson_pc', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='抽水成數(%)')),
                ('remain_commisson', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='未領取抽水額')),
                ('child_player_count', models.PositiveIntegerField(default=0, verbose_name='下層玩家數')),
                ('child_player_total_run', models.PositiveIntegerField(default=0, verbose_name='下層玩家總局數')),
                ('child_agent_player', models.PositiveIntegerField(default=0, verbose_name='下層代理數')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('agent_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='代理玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='AddValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('2', '補償'), ('3', '信用卡儲值')], default='2', max_length=1, verbose_name='儲值/補償')),
                ('gold', models.IntegerField(default=0, verbose_name='金額')),
                ('description', models.TextField(blank=True, null=True, verbose_name='補幣事由')),
                ('admin_account', models.CharField(max_length=150, verbose_name='管理者帳號')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player')),
            ],
        ),
    ]
