# Generated by Django 3.0 on 2020-05-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=20, verbose_name='帳號')),
                ('user_password', models.CharField(max_length=20, verbose_name='密碼')),
                ('user_name', models.CharField(max_length=20, verbose_name='管理員名稱')),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='手機號碼')),
                ('level', models.CharField(choices=[('1', '代理玩家'), ('2', '一般客服'), ('3', '客服主管'), ('8', '系統主管'), ('9', '工程師')], default='8', max_length=1, verbose_name='系統身份')),
                ('player_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='代理玩家ID')),
                ('create_user', models.CharField(max_length=20, verbose_name='創建者帳號')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='最後登入時間')),
                ('modify_user', models.CharField(max_length=20, verbose_name='異動者帳號')),
                ('last_modify_date', models.DateTimeField(auto_now=True, verbose_name='最後異動時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否被刪除')),
                ('deleted_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='刪除者帳號')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='帳號刪除時間')),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify_date', models.DateTimeField(auto_now=True, verbose_name='登入時間')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Account', verbose_name='登入帳號ID')),
            ],
        ),
    ]
