# Generated by Django 3.0 on 2020-05-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0002_account_logininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='account',
            name='pphone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='手機號碼'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='手機號碼'),
        ),
    ]
