# Generated by Django 3.0 on 2020-05-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0003_auto_20200521_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pphone_number',
            new_name='phone_number',
        ),
    ]
