# Generated by Django 3.0 on 2020-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0004_auto_20200521_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logininfo',
            old_name='last_modify_date',
            new_name='login_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='gamerun',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='goldflowsummary',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='introductiongold',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間'),
        ),
    ]
