# Generated by Django 3.0 on 2020-05-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0005_auto_20200522_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePWDLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=20, verbose_name='帳號名稱')),
                ('old_password', models.CharField(max_length=20, verbose_name='舊密碼')),
                ('new_password', models.CharField(max_length=20, verbose_name='新密碼')),
                ('modify_user', models.CharField(max_length=20, verbose_name='異動者帳號名稱')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='異動時間')),
            ],
        ),
        migrations.AddField(
            model_name='logininfo',
            name='login_system',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='登入系統代碼'),
        ),
    ]
