# Generated by Django 3.0 on 2020-06-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0006_auto_20200522_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipinfo',
            old_name='iemi',
            new_name='imei',
        ),
    ]
