# Generated by Django 3.0 on 2020-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0009_auto_20200831_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最後登入時間'),
        ),
    ]
