# Generated by Django 3.0 on 2020-09-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0010_player_last_login_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='主題')),
                ('message', models.CharField(max_length=500, verbose_name='訊息內容')),
                ('operator', models.CharField(max_length=20, verbose_name='操作者名稱')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='操作時間')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinReceiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Bulletin', verbose_name='公告記錄ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
    ]
