# Generated by Django 3.0 on 2020-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0011_bulletin_bulletinreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='base',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='底數'),
        ),
    ]
