# Generated by Django 3.0 on 2020-10-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0013_auto_20201019_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvalue',
            name='old_gold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='原始金額'),
        ),
        migrations.AddField(
            model_name='goldflow',
            name='old_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='原始金額'),
        ),
        migrations.AddField(
            model_name='playergold',
            name='old_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='原始金額'),
        ),
        migrations.AlterField(
            model_name='addvalue',
            name='admin_account',
            field=models.CharField(max_length=20, verbose_name='管理者帳號'),
        ),
        migrations.AlterField(
            model_name='goldflow',
            name='admin_account',
            field=models.CharField(default='', max_length=20, verbose_name='管理者帳號'),
        ),
    ]
