# Generated by Django 3.0 on 2020-10-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0015_auto_20201021_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerwallet',
            name='amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='金額'),
        ),
    ]
