# Generated by Django 3.0 on 2020-10-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0016_auto_20201022_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bonus_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True, verbose_name='抽水成數(%)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='return_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True, verbose_name='給上層代理的回饋成數(%)'),
        ),
    ]
