# Generated by Django 3.0 on 2020-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0017_auto_20201022_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player1_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1起始金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player1_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1輸贏金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2起始金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2輸贏金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player3_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3起始金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player3_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3輸贏金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player4_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4起始金額'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player4_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4輸贏金額'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='total_commission',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='總抽水金額'),
        ),
    ]
