# Generated by Django 3.0 on 2020-10-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0018_auto_20201023_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergold',
            name='run_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='遊戲局號(回播碼)'),
        ),
        migrations.AlterField(
            model_name='playergold',
            name='type',
            field=models.CharField(choices=[('11', '遊戲儲值'), ('12', '贈送'), ('13', '受贈'), ('14', '抽水錢包提領'), ('15', '牌局輸贏'), ('16', '官方補幣')], default='11', max_length=2, verbose_name='類別'),
        ),
    ]
