# Generated by Django 3.0 on 2020-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0019_auto_20201023_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='player1_start_gold',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player1_win',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player2_start_gold',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player2_win',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player3_start_gold',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player3_win',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player4_start_gold',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player4_win',
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player1_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1起始金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player1_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1輸贏金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player2_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2起始金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player2_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2輸贏金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player3_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3起始金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player3_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3輸贏金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player4_start_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4起始金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player4_win',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4輸贏金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='total_agent_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='總代理抽水金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='total_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='總官方抽水金額'),
        ),
    ]
