# Generated by Django 3.0 on 2020-10-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0020_auto_20201025_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldflow',
            name='type',
            field=models.CharField(choices=[('1', '發行金幣'), ('2', '補償'), ('3', '信用卡儲值'), ('4', '介紹金'), ('5', '抽水'), ('6', '體驗金'), ('7', '代理抽水')], default='2', max_length=1, verbose_name='類別'),
        ),
    ]
