# Generated by Django 3.0 on 2020-10-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0021_auto_20201027_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerun',
            name='bookmarker_player',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='莊家'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player1_settle_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1結算金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player2_settle_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2結算金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player3_settle_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3結算金額'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player4_settle_gold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4結算金額'),
        ),
        migrations.AlterField(
            model_name='gamerun',
            name='player1_win',
            field=models.IntegerField(default=0, verbose_name='玩家ID1成績'),
        ),
        migrations.AlterField(
            model_name='gamerun',
            name='player2_win',
            field=models.IntegerField(default=0, verbose_name='玩家ID2成績'),
        ),
        migrations.AlterField(
            model_name='gamerun',
            name='player3_win',
            field=models.IntegerField(default=0, verbose_name='玩家ID3成績'),
        ),
        migrations.AlterField(
            model_name='gamerun',
            name='player4_win',
            field=models.IntegerField(default=0, verbose_name='玩家ID4成績'),
        ),
        migrations.CreateModel(
            name='PlayerGameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banker_count', models.IntegerField(default=0, verbose_name='連莊次數')),
                ('score', models.IntegerField(default=0, verbose_name='總成績')),
                ('start_gold', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='起始金額')),
                ('settle_gold', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='結算金額')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='官方抽水金額')),
                ('agent_commisson', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='代理抽水金額')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.GameRoom', verbose_name='GameRoomID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
    ]
