# Generated by Django 3.0 on 2020-10-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0022_auto_20201030_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerun',
            name='player1_agent_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1代理抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player1_corp_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID1官方抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player2_agent_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2代理抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player2_corp_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID2官方抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player3_agent_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3代理抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player3_corp_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID3官方抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player4_agent_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4代理抽水'),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='player4_corp_bonus',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20, verbose_name='玩家ID4官方抽水'),
        ),
    ]
