# Generated by Django 3.0 on 2020-11-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0025_playerroundresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerun',
            old_name='bookmarker_player',
            new_name='banker_player',
        ),
        migrations.RenameField(
            model_name='playerroundresult',
            old_name='agent_commisson',
            new_name='agent_bonus',
        ),
        migrations.RenameField(
            model_name='playerroundresult',
            old_name='commission',
            new_name='corp_bonus',
        ),
    ]
