# Generated by Django 3.0 on 2020-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0026_auto_20201104_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='鑽石'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip_type',
            field=models.CharField(choices=[('0', ''), ('10', '賭徒'), ('50', '賭王'), ('100', '賭霸'), ('500', '賭聖'), ('1000', '賭俠'), ('2000', '賭神')], default='0', max_length=4, verbose_name='VIP等級'),
        ),
        migrations.AlterField(
            model_name='playergold',
            name='type',
            field=models.CharField(choices=[('11', '遊戲儲值'), ('12', '贈送'), ('13', '受贈'), ('14', '抽水錢包提領'), ('15', '牌局輸贏'), ('16', '官方補幣'), ('17', 'VIP儲值')], default='11', max_length=2, verbose_name='類別'),
        ),
    ]
