# Generated by Django 3.0 on 2020-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0027_auto_20201107_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bindcode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='綁定邀請碼'),
        ),
        migrations.AlterField(
            model_name='player',
            name='linkcode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='玩家邀請碼'),
        ),
    ]
