# Generated by Django 3.0 on 2020-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0028_auto_20201107_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vip_type',
            field=models.PositiveIntegerField(choices=[(0, ''), (10, '賭徒'), (50, '賭王'), (100, '賭霸'), (500, '賭聖'), (1000, '賭俠'), (2000, '賭神')], default=0, verbose_name='VIP等級'),
        ),
    ]
