# Generated by Django 3.0 on 2020-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0029_auto_20201109_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='area',
            field=models.CharField(choices=[('1', '一般'), ('2', '富豪'), ('3', '私人')], default='1', max_length=1, verbose_name='區域'),
        ),
    ]
