# Generated by Django 3.0 on 2020-11-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0031_auto_20201110_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_type', models.PositiveIntegerField(choices=[(10, '賭徒'), (50, '賭王'), (100, '賭霸'), (500, '賭聖'), (1000, '賭俠'), (2000, '賭神')], default=10, verbose_name='VIP等級')),
                ('layer', models.PositiveIntegerField(default=1, verbose_name='Layer')),
                ('seat', models.PositiveIntegerField(default=1, verbose_name='SEAT')),
                ('player', models.PositiveIntegerField(default=0, verbose_name='玩家ID')),
                ('upper_player', models.PositiveIntegerField(default=0, verbose_name='上層')),
                ('bind_player', models.PositiveIntegerField(default=0, verbose_name='推薦人玩家ID')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
            ],
        ),
        migrations.CreateModel(
            name='VIPSummary',
            fields=[
                ('vip', models.PositiveIntegerField(choices=[(10, '賭徒'), (50, '賭王'), (100, '賭霸'), (500, '賭聖'), (1000, '賭俠'), (2000, '賭神')], primary_key=True, serialize=False, verbose_name='VIP等級')),
                ('now_layer', models.PositiveIntegerField(default=1, verbose_name='Layer')),
                ('now_seat', models.PositiveIntegerField(default=1, verbose_name='SEAT')),
                ('last_modify_date', models.DateTimeField(blank=True, null=True, verbose_name='最後異動時間')),
            ],
        ),
        migrations.AddField(
            model_name='goldflowsummary',
            name='star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='鑽石數量'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip1000_seat',
            field=models.IntegerField(default=-1, verbose_name='VIP1000最上層位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip100_seat',
            field=models.IntegerField(default=-1, verbose_name='VIP100最上層位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip10_seat',
            field=models.IntegerField(default=-1, verbose_name='VIP10最上層位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip2000_seat',
            field=models.IntegerField(default=-1, verbose_name='VIP2000最上層位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip500_seat',
            field=models.IntegerField(default=-1, verbose_name='VIP500最上層位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip50_seat',
            field=models.IntegerField(default=-1, verbose_name='VIP50最上層位置'),
        ),
        migrations.CreateModel(
            name='StarFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starflow_type', models.CharField(choices=[('1', 'VIP儲值'), ('2', '見點獎金'), ('3', '匹配獎金')], default='1', max_length=1, verbose_name='類別')),
                ('old_star', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='未異動前鑽石數量')),
                ('star', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='異動鑽石數量')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_type', models.CharField(choices=[('2', '見點獎金'), ('3', '匹配獎金')], default='2', max_length=1, verbose_name='類別')),
                ('obj_playerid', models.PositiveIntegerField(verbose_name='來源玩家ID')),
                ('old_star', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='原始鑽石數量')),
                ('star', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='異動鑽石數量')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
    ]
