# Generated by Django 3.0 on 2020-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0032_auto_20201111_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bindcode',
            field=models.PositiveIntegerField(default=0, verbose_name='綁定邀請碼'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bonus_ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='抽水成數(%)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='linkcode',
            field=models.PositiveIntegerField(default=0, verbose_name='玩家邀請碼'),
        ),
        migrations.AlterField(
            model_name='player',
            name='return_ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='給上層代理的回饋成數(%)'),
        ),
    ]
