# Generated by Django 3.0 on 2020-11-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0034_auto_20201112_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='lower1_player',
            field=models.PositiveIntegerField(default=0, verbose_name='下層位置1的玩家ID'),
        ),
        migrations.AddField(
            model_name='vip',
            name='lower1_seat',
            field=models.PositiveIntegerField(default=0, verbose_name='下層位置1'),
        ),
        migrations.AddField(
            model_name='vip',
            name='lower2_player',
            field=models.PositiveIntegerField(default=0, verbose_name='下層位置2的玩家ID'),
        ),
        migrations.AddField(
            model_name='vip',
            name='lower2_seat',
            field=models.PositiveIntegerField(default=0, verbose_name='下層位置2'),
        ),
        migrations.AddField(
            model_name='vip',
            name='lower3_player',
            field=models.PositiveIntegerField(default=0, verbose_name='下層位置3的玩家ID'),
        ),
        migrations.AddField(
            model_name='vip',
            name='lower3_seat',
            field=models.PositiveIntegerField(default=0, verbose_name='下層位置3'),
        ),
        migrations.AddField(
            model_name='vip',
            name='upper_seat',
            field=models.PositiveIntegerField(default=0, verbose_name='上層位置'),
        ),
    ]
