# Generated by Django 3.0 on 2020-11-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0035_auto_20201112_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPSeat',
            fields=[
                ('seat', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Seat')),
                ('layer', models.PositiveIntegerField(default=0, verbose_name='Layer')),
                ('upper_seat', models.PositiveIntegerField(default=1, verbose_name='UpperSeat')),
                ('lower1_seat', models.PositiveIntegerField(default=1, verbose_name='Lower1Seat')),
                ('lower2_seat', models.PositiveIntegerField(default=1, verbose_name='Lower2Seat')),
                ('lower3_seat', models.PositiveIntegerField(default=1, verbose_name='Lower3Seat')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
