# Generated by Django 3.0 on 2020-11-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0039_auto_20201116_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.VIPSeat', verbose_name='SEAT'),
        ),
    ]
