# Generated by Django 3.0 on 2021-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0041_playerlogininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bindcode',
            field=models.CharField(default='', max_length=8, verbose_name='綁定邀請碼'),
        ),
        migrations.AlterField(
            model_name='player',
            name='linkcode',
            field=models.CharField(default='', max_length=8, verbose_name='玩家邀請碼'),
        ),
    ]
