# Generated by Django 3.0 on 2021-02-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0042_auto_20210106_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvalue',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='addvalue',
            name='old_gold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='原始金額/鑽石'),
        ),
        migrations.AlterField(
            model_name='addvalue',
            name='type',
            field=models.CharField(choices=[('2', '補償'), ('3', '信用卡儲值'), ('4', '玩家入金')], default='2', max_length=1, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bindcode',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='綁定邀請碼'),
        ),
        migrations.AlterField(
            model_name='player',
            name='linkcode',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='玩家邀請碼'),
        ),
        migrations.AlterField(
            model_name='playerstar',
            name='star_type',
            field=models.CharField(choices=[('2', '見點獎金'), ('3', '匹配獎金'), ('4', '入金'), ('5', '出金')], default='2', max_length=1, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='starflow',
            name='starflow_type',
            field=models.CharField(choices=[('1', 'VIP儲值'), ('2', '見點獎金'), ('3', '匹配獎金'), ('4', '入金'), ('5', '出金')], default='1', max_length=1, verbose_name='類別'),
        ),
    ]
