# Generated by Django 3.0 on 2021-02-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0043_auto_20210202_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bind_player',
            field=models.PositiveIntegerField(default=0, verbose_name='推薦人玩家ID'),
        ),
    ]
