# Generated by Django 3.0 on 2021-03-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0045_auto_20210304_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_addr', models.CharField(blank=True, default='', max_length=100, verbose_name='錢包位址')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='鑽石')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', '已出金'), ('2', '審核中')], default='2', max_length=1, verbose_name='狀態')),
                ('old_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='原始鑽石')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
    ]
