# Generated by Django 3.0 on 2021-03-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0046_playerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='playerstar',
            name='star_type',
            field=models.CharField(choices=[('2', '見點獎金'), ('3', '匹配獎金'), ('4', '入金'), ('5', '出金'), ('6', '官方補幣'), ('7', '贈禮'), ('8', '收禮')], default='2', max_length=2, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='starflow',
            name='starflow_type',
            field=models.CharField(choices=[('1', '玩家購買配套'), ('2', '見點獎金'), ('3', '匹配獎金'), ('4', '入金'), ('5', '玩家出金'), ('6', '補幣')], default='1', max_length=1, verbose_name='類別'),
        ),
    ]
