# Generated by Django 3.0 on 2021-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0048_auto_20210308_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerorder',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出金確認時間'),
        ),
        migrations.AddField(
            model_name='playerorder',
            name='done_user',
            field=models.CharField(default='', max_length=20, verbose_name='出金確認者帳號'),
        ),
    ]
