# Generated by Django 3.0 on 2021-03-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0049_auto_20210308_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvalue',
            name='jewel_type',
            field=models.PositiveIntegerField(choices=[(1, '金幣'), (2, '鑽石')], default=1, verbose_name='貨幣種類'),
        ),
    ]
