# Generated by Django 3.0 on 2021-03-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0050_addvalue_jewel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPSeqn',
            fields=[
                ('vip_type', models.PositiveIntegerField(choices=[(1, '賭徒'), (2, '賭王'), (3, '賭霸'), (4, '賭聖'), (5, '賭俠'), (6, '賭神')], primary_key=True, serialize=False, verbose_name='VIP等級')),
                ('vip_seqn', models.IntegerField(default=0, verbose_name='目前編號')),
            ],
        ),
        migrations.CreateModel(
            name='VIPTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('vip_type', models.PositiveIntegerField(choices=[(0, ''), (1, '賭徒'), (2, '賭王'), (3, '賭霸'), (4, '賭聖'), (5, '賭俠'), (6, '賭神')], default=1, verbose_name='VIP等級')),
                ('seat', models.PositiveIntegerField(default=0, verbose_name='Seat')),
                ('layer', models.PositiveIntegerField(default=0, verbose_name='Layer')),
                ('parent', models.PositiveIntegerField(default=0, verbose_name='Parent')),
                ('child1', models.PositiveIntegerField(default=0, verbose_name='Child1')),
                ('child2', models.PositiveIntegerField(default=0, verbose_name='Child2')),
                ('child3', models.PositiveIntegerField(default=0, verbose_name='Child3')),
                ('branch_count', models.PositiveIntegerField(default=0, verbose_name='分支數量')),
                ('bind_player', models.PositiveIntegerField(default=0, verbose_name='推薦人玩家ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='vip_type',
            field=models.PositiveIntegerField(choices=[(0, ''), (1, '賭徒'), (2, '賭王'), (3, '賭霸'), (4, '賭聖'), (5, '賭俠'), (6, '賭神')], default=0, verbose_name='VIP等級'),
        ),
        migrations.AlterField(
            model_name='playerstar',
            name='obj_playerid',
            field=models.PositiveIntegerField(verbose_name='對象玩家ID'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vip_type',
            field=models.PositiveIntegerField(choices=[(0, ''), (1, '賭徒'), (2, '賭王'), (3, '賭霸'), (4, '賭聖'), (5, '賭俠'), (6, '賭神')], default=10, verbose_name='VIP等級'),
        ),
        migrations.AddField(
            model_name='viptree',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID'),
        ),
    ]
