# Generated by Django 3.0 on 2021-03-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0051_auto_20210312_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIPSummary',
        ),
    ]
