# Generated by Django 3.0 on 2021-03-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0052_auto_20210314_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPBonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('vip_type', models.PositiveIntegerField(choices=[(1, '賭徒'), (2, '賭王'), (3, '賭霸'), (4, '賭聖'), (5, '賭俠'), (6, '賭神')], default=1, verbose_name='VIP等級')),
                ('seat', models.PositiveIntegerField(default=0, verbose_name='Seat')),
                ('level_player', models.PositiveIntegerField(default=0, verbose_name='見點獎金玩家ID')),
                ('level_bouns', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='見點獎金')),
                ('match_player', models.PositiveIntegerField(default=0, verbose_name='匹配獎金玩家ID')),
                ('match_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='匹配獎金')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamecore.Player', verbose_name='玩家ID')),
            ],
        ),
    ]
