# Generated by Django 3.0 on 2021-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0053_vipbonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIP',
        ),
        migrations.DeleteModel(
            name='VIPSeat',
        ),
    ]
