# Generated by Django 3.0 on 2021-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0054_auto_20210323_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldflow',
            name='type',
            field=models.CharField(choices=[('1', '發行金幣'), ('2', '補幣'), ('6', '抽水'), ('7', '玩家購買籌碼'), ('8', '玩家兌換籌碼')], default='2', max_length=1, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='playergold',
            name='type',
            field=models.CharField(choices=[('1', '購買配套'), ('2', '官方補幣'), ('3', '贈禮'), ('4', '收禮'), ('5', '遊戲輸贏'), ('6', '抽水'), ('7', '購買籌碼'), ('8', '兌換籌碼')], default='11', max_length=2, verbose_name='類別'),
        ),
    ]
