# Generated by Django 3.0 on 2021-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0055_auto_20210325_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='vip1000_seat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vip100_seat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vip10_seat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vip2000_seat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vip500_seat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vip50_seat',
        ),
        migrations.AddField(
            model_name='player',
            name='vip1_seat',
            field=models.IntegerField(default=0, verbose_name='VIP1第一個位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip2_seat',
            field=models.IntegerField(default=0, verbose_name='VIP2第一個位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip3_seat',
            field=models.IntegerField(default=0, verbose_name='VIP3第一個位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip4_seat',
            field=models.IntegerField(default=0, verbose_name='VIP4第一個位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip5_seat',
            field=models.IntegerField(default=0, verbose_name='VIP5第一個位置'),
        ),
        migrations.AddField(
            model_name='player',
            name='vip6_seat',
            field=models.IntegerField(default=0, verbose_name='VIP6第一個位置'),
        ),
    ]
