# Generated by Django 3.0 on 2021-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0057_auto_20210407_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gold_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='金幣'),
        ),
        migrations.AlterField(
            model_name='player',
            name='star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='鑽石'),
        ),
    ]
