# Generated by Django 3.0 on 2021-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0058_auto_20210408_0046'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='addvalue',
            index=models.Index(fields=['type', 'jewel_type', 'created_date'], name='gamecore_ad_type_9b0457_idx'),
        ),
    ]
